spring.application.name=martin
spring.datasource.password=db_prod_secret_2026
external.api.key=sk-12345-spring-io-demo-key

# DANGEROUS: Enabling all endpoints and making them public
management.endpoints.web.exposure.include=*
# Actuator exposure (The Leak)
management.endpoints.web.exposure.include=env,configprops
management.endpoint.env.show-values=ALWAYS
management.endpoint.configprops.show-values=ALWAYS