spring.application.name=martin
spring.datasource.password=db_prod_secret_2026
external.api.key=sk-12345-spring-io-demo-key

# DANGEROUS: Enabling all endpoints and making them public
management.endpoints.web.exposure.include=*
# Actuator exposure (The Leak)
management.endpoint.env.show-values=NEVER
management.endpoint.configprops.show-values=ALWAYS
# Define additional keys that should be masked (regex supported)
management.endpoint.sanitizer.keys-to-sanitize=*password*,secret,key,token,.*credentials.*
management.endpoint.configprops.keys-to-sanitize=*password*,secret,key,token,.*credentials.*
management.endpoint.env.keys-to-sanitize=*password*,spring.datasource.password, secret,key,token,.*credentials.*
management.endpoint.env.additional-keys-to-sanitize=*password*,secret,key,token,.*credentials.*
management.endpoint.configprops.additional-keys-to-sanitize=*password*,secret,key,token,.*credentials.*
management.endpoint.sanitizer.additional-keys-to-sanitize=*password*,secret,key,token,.*credentials.*
